name = "vegvisr-onboarding"
compatibility_date = "2024-09-24"

[vars]
PUBLIC_APP_URL = "http://localhost:5173"
MAGIC_LINK_WEBHOOK_URL = ""
ONBOARDING_WEBHOOK_URL = ""
ONBOARDING_EMAIL_ENDPOINT = ""
ONBOARDING_EMAIL_RECIPIENT = ""
GOOGLE_CLIENT_ID = ""
GOOGLE_REDIRECT_URI = ""
GOOGLE_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"
GOOGLE_USERINFO_ENDPOINT = "https://www.googleapis.com/oauth2/v3/userinfo"
OAUTH_EXCHANGE_URL = ""
CORS_ALLOWED_ORIGINS = ""

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "vegvisr-onboarding"
database_id = "a93e63a9-3dd2-4cb8-9cb6-e33be7bae3d5"
